<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { adminApi, type TicketCategory } from '@/api'; import { apiErrorMessage } from '@/lib/api-error'; import { useI18n } from '@/stores/i18n'; import { promptValue } from '@/stores/dialog';
const i18n = useI18n(); const items = ref<TicketCategory[]>([]); const name = ref(''); const error = ref(''); const busy = ref(false);
async function load() { try { items.value = (await adminApi.ticketCategories()).items; } catch (e) { error.value = apiErrorMessage(e); } }
async function add() { if (!name.value.trim() || busy.value) return; busy.value = true; try { await adminApi.createTicketCategory(name.value); name.value = ''; await load(); } catch (e) { error.value = apiErrorMessage(e); } finally { busy.value = false; } }
async function toggle(item: TicketCategory) { try { await adminApi.updateTicketCategory(item.id, { hidden: !item.hidden }); await load(); } catch (e) { error.value = apiErrorMessage(e); } }
async function rename(item: TicketCategory) { const value = await promptValue(i18n.t('ticket.category_name'), item.name); if (value === null || !value.trim() || value.trim() === item.name) return; try { await adminApi.updateTicketCategory(item.id, { name: value.trim() }); await load(); } catch (e) { error.value = apiErrorMessage(e); } }
onMounted(load);
</script>
<template><PageHeader :title="i18n.t('ticket.category_manage')" /><p v-if="error" class="alert alert-danger">{{ error }}</p><section class="panel mb-4 flex gap-2"><AppInput v-model="name" class="flex-1" maxlength="80" :placeholder="i18n.t('ticket.category_name')" @keyup.enter="add" /><AppButton class="btn-primary" :loading="busy" @click="add">{{ i18n.t('ticket.category_add') }}</AppButton></section><section class="panel !p-0 overflow-x-auto"><table class="table"><thead><tr><th>{{ i18n.t('ticket.category_name') }}</th><th>{{ i18n.t('ticket.category_state') }}</th><th></th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ item.name }}</td><td><span class="badge" :class="item.hidden ? '' : 'badge-success'">{{ item.hidden ? i18n.t('ticket.category_hidden') : i18n.t('ticket.category_visible') }}</span></td><td class="text-right"><AppButton class="btn-sm" @click="rename(item)">{{ i18n.t('common.edit') }}</AppButton><AppButton class="btn-sm ml-2" @click="toggle(item)">{{ item.hidden ? i18n.t('ticket.category_restore') : i18n.t('ticket.category_hide') }}</AppButton></td></tr></tbody></table></section></template>
