ALTER TABLE textures ADD COLUMN score_refund_basis INTEGER NOT NULL DEFAULT 0;
ALTER TABLE textures ADD COLUMN score_award INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN score_paid INTEGER NOT NULL DEFAULT 0;
