-- PostgreSQL 版迁移（自 packages/db/migrations/0000_init.sql 翻译）。
-- 由 Node 迁移执行器应用；D1 路径不使用本目录。

-- Blessing Skin 初始 schema
--
-- 这份迁移是**手写**的，不是 drizzle-kit 生成的。原因：
--   • users.email / players.name 需要不区分大小写的唯一索引
--     （用 lower(col) 函数唯一索引实现，等价于 SQLite 的 COLLATE NOCASE；
--      不显式处理大小写就会出现 `Notch` 与 `notch` 都能注册的行为变更）
--   • users/players/textures 需要 IDENTITY 保证 id 永不复用
--     （id 出现在 URL 里，复用会让新对象继承已删除对象的地址）
--   • settings 的主键是 (key, locale) 复合键
--
-- 存储约定：布尔用 BIGINT 存 0/1，时间戳为 epoch 毫秒 BIGINT，JSON 用 TEXT。
-- 设计说明见 docs/rewrite/04-database-schema.md
--
-- 注意：users.avatar_texture_id / players.skin_texture_id / players.cape_texture_id
-- 前向引用 textures(id)（textures 建在后面），改为文件末尾的
-- ALTER TABLE ... ADD FOREIGN KEY，表创建顺序与 SQLite 版保持一致。

-- ─────────────────────────────────────────────────────────────────────────────
-- users
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE users (
  id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email                    TEXT    NOT NULL,
  email_verified_at        BIGINT,
  nickname                 TEXT    NOT NULL DEFAULT '',
  locale                   TEXT,
  score                    BIGINT NOT NULL DEFAULT 1000,
  avatar_texture_id        BIGINT,

  -- 凭据。password_hash 是自描述字符串 `<algo>:<payload>`，
  -- 因此迁移期旧哈希与新 PBKDF2 哈希可以共存一列，按第一段分发即可。
  password_hash            TEXT    NOT NULL,
  password_rehash_required BIGINT NOT NULL DEFAULT 0,

  role                     TEXT    NOT NULL DEFAULT 'normal',
  registration_ip          TEXT,
  is_dark_mode             BIGINT NOT NULL DEFAULT 0,
  last_sign_at             BIGINT,
  created_at               BIGINT NOT NULL,
  updated_at               BIGINT NOT NULL
);

CREATE UNIQUE INDEX users_email_unique ON users(lower(email));
CREATE INDEX users_role_idx       ON users(role);
CREATE INDEX users_created_at_idx ON users(created_at);
CREATE INDEX users_reg_ip_idx     ON users(registration_ip);

-- ─────────────────────────────────────────────────────────────────────────────
-- sessions —— 服务端会话，可撤销。存的是 sha256(token)，原始令牌从不落库。
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE sessions (
  id                  TEXT    PRIMARY KEY,
  user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at          BIGINT NOT NULL,
  last_seen_at        BIGINT NOT NULL,
  expires_at          BIGINT NOT NULL,
  absolute_expires_at BIGINT NOT NULL,
  ip                  TEXT,
  user_agent          TEXT,
  revoked_at          BIGINT
);

CREATE INDEX sessions_user_id_idx    ON sessions(user_id);
CREATE INDEX sessions_expires_at_idx ON sessions(expires_at);

-- ─────────────────────────────────────────────────────────────────────────────
-- players
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE players (
  id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name            TEXT    NOT NULL,
  skin_texture_id BIGINT,
  cape_texture_id BIGINT,
  created_at      BIGINT,
  updated_at      BIGINT NOT NULL
);

CREATE UNIQUE INDEX players_name_unique ON players(lower(name));
CREATE INDEX players_user_id_idx ON players(user_id);
CREATE INDEX players_skin_idx    ON players(skin_texture_id);
CREATE INDEX players_cape_idx    ON players(cape_texture_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- textures —— 只有元数据；字节位于 R2 键 `textures/<hash>.png`
--
-- 注意 hash **有意不加唯一约束**：旧库允许同哈希多行（去重规则依赖 uploader
-- 与可见性），加约束会强制重映射 tid，而 R2 的对象身份已由哈希键去重。
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE textures (
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hash        TEXT    NOT NULL,
  kind        TEXT    NOT NULL,
  model       TEXT,
  name        TEXT    NOT NULL,
  uploader_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  size_bytes  BIGINT NOT NULL,
  visibility  TEXT    NOT NULL DEFAULT 'public',
  width       BIGINT NOT NULL,
  height      BIGINT NOT NULL,
  likes       BIGINT NOT NULL DEFAULT 0,
  created_at  BIGINT NOT NULL,
  updated_at  BIGINT NOT NULL
);

CREATE INDEX textures_hash_idx        ON textures(hash);
CREATE INDEX textures_uploader_idx    ON textures(uploader_id);
CREATE INDEX textures_vis_created_idx ON textures(visibility, created_at DESC);
CREATE INDEX textures_vis_likes_idx   ON textures(visibility, likes DESC);
CREATE INDEX textures_kind_vis_idx    ON textures(kind, visibility);

-- 前向引用补齐：users / players 对 textures 的外键
ALTER TABLE users   ADD CONSTRAINT users_avatar_texture_fk   FOREIGN KEY (avatar_texture_id) REFERENCES textures(id) ON DELETE SET NULL;
ALTER TABLE players ADD CONSTRAINT players_skin_texture_fk   FOREIGN KEY (skin_texture_id)   REFERENCES textures(id) ON DELETE SET NULL;
ALTER TABLE players ADD CONSTRAINT players_cape_texture_fk   FOREIGN KEY (cape_texture_id)   REFERENCES textures(id) ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- closet —— 取代旧 user_closet（旧表没有主键也没有索引）
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE closet (
  user_id    BIGINT NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
  texture_id BIGINT NOT NULL REFERENCES textures(id) ON DELETE CASCADE,
  item_name  TEXT,
  created_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, texture_id)
);

CREATE INDEX closet_texture_id_idx   ON closet(texture_id);
CREATE INDEX closet_user_created_idx ON closet(user_id, created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- reports
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE reports (
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  texture_id  BIGINT NOT NULL REFERENCES textures(id) ON DELETE CASCADE,
  uploader_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  reporter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reason      TEXT    NOT NULL,
  status      TEXT    NOT NULL DEFAULT 'pending',
  reviewer_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  resolution  TEXT,
  created_at  BIGINT NOT NULL,
  reviewed_at BIGINT
);

CREATE UNIQUE INDEX reports_reporter_texture_unique ON reports(reporter_id, texture_id);
CREATE INDEX reports_status_created_idx ON reports(status, created_at DESC);
CREATE INDEX reports_texture_idx        ON reports(texture_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- notifications —— 取代 Laravel 的 UUID morph 表
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE notifications (
  id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type       TEXT    NOT NULL,
  title      TEXT    NOT NULL,
  body       TEXT,
  read_at    BIGINT,
  created_at BIGINT NOT NULL
);

CREATE INDEX notifications_user_unread_idx ON notifications(user_id, read_at, created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- settings —— 运行时可改的配置。部署配置留在 wrangler 里。
--
-- locale 默认 '' 而不是 NULL：主键里的 NULL 彼此不相等，
-- 用 NULL 的话 (key, NULL) 行不会唯一。
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE settings (
  key        TEXT    NOT NULL,
  locale     TEXT    NOT NULL DEFAULT '',
  value      TEXT    NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (key, locale)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 邮箱验证令牌 —— 一次性、会过期。
-- 旧版用的是**永久有效且可重复使用**的签名 URL，这里是有意收紧。
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE verification_tokens (
  id          TEXT    PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  email       TEXT    NOT NULL,
  created_at  BIGINT NOT NULL,
  expires_at  BIGINT NOT NULL,
  consumed_at BIGINT
);

CREATE INDEX verification_tokens_user_idx ON verification_tokens(user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 密码重置令牌 —— 一次性、会过期。旧版在 1 小时窗口内可重复使用。
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE password_reset_tokens (
  id          TEXT    PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at  BIGINT NOT NULL,
  expires_at  BIGINT NOT NULL,
  consumed_at BIGINT
);

CREATE INDEX password_reset_tokens_user_idx ON password_reset_tokens(user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- auth_attempts —— 权威的暴力破解锁定依据。
-- 与最终一致的 Cloudflare Rate Limiting binding 互补：后者适合吸收洪水，
-- 但无法强制精确计数，而锁定策略需要精确计数。
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE auth_attempts (
  id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ip         TEXT    NOT NULL,
  identifier TEXT,
  kind       TEXT    NOT NULL,
  succeeded  BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL
);

CREATE INDEX auth_attempts_ip_kind_created_idx ON auth_attempts(ip, kind, created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- audit_log —— 管理员操作记录。小、只追加、保留成本低。
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE audit_log (
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  actor_id    BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action      TEXT    NOT NULL,
  target_type TEXT,
  target_id   BIGINT,
  detail      TEXT,
  created_at  BIGINT NOT NULL
);

CREATE INDEX audit_log_created_idx ON audit_log(created_at DESC);
