-- PostgreSQL 版迁移（自 packages/db/migrations/0008_pigeon.sql 翻译）。
-- 由 Node 迁移执行器应用；D1 路径不使用本目录。

CREATE TABLE pigeon_api_keys (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  secret_hash TEXT NOT NULL UNIQUE,
  prefix TEXT NOT NULL,
  scopes TEXT NOT NULL,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  enabled BIGINT NOT NULL DEFAULT 1,
  revoked_at BIGINT,
  created_at BIGINT NOT NULL,
  last_used_at BIGINT,
  usage_count BIGINT NOT NULL DEFAULT 0,
  window_start BIGINT NOT NULL DEFAULT 0,
  window_count BIGINT NOT NULL DEFAULT 0
);

-- name 的 COLLATE NOCASE UNIQUE → lower(name) 唯一索引
CREATE TABLE pigeon_packs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  server_type TEXT NOT NULL,
  enabled BIGINT NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX pigeon_packs_name_nocase_unique ON pigeon_packs(lower(name));

CREATE TABLE pigeon_votes (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL CHECK (status IN ('draft', 'published', 'closed', 'cancelled')),
  starts_at BIGINT NOT NULL,
  ends_at BIGINT NOT NULL CHECK (ends_at > starts_at),
  max_choices BIGINT NOT NULL CHECK (max_choices >= 1),
  results_policy TEXT NOT NULL CHECK (results_policy IN ('after_close', 'after_vote', 'always')),
  registered_before BIGINT,
  min_score BIGINT NOT NULL DEFAULT 0,
  require_verified BIGINT NOT NULL DEFAULT 0,
  play_rules TEXT NOT NULL DEFAULT '[]',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  closed_at BIGINT,
  archived_at BIGINT,
  version BIGINT NOT NULL DEFAULT 1,
  mutation_key TEXT,
  review_required BIGINT NOT NULL DEFAULT 0,
  review_notes TEXT NOT NULL DEFAULT '[]'
);
CREATE INDEX pigeon_votes_window ON pigeon_votes(status, archived_at, starts_at, ends_at);

CREATE TABLE pigeon_vote_options (
  id TEXT PRIMARY KEY,
  vote_id TEXT NOT NULL REFERENCES pigeon_votes(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  position BIGINT NOT NULL,
  UNIQUE(vote_id, position)
);

CREATE TABLE pigeon_ballots (
  id TEXT PRIMARY KEY,
  vote_id TEXT NOT NULL REFERENCES pigeon_votes(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  voter_name TEXT NOT NULL,
  option_ids TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  ip TEXT,
  revision BIGINT NOT NULL DEFAULT 1,
  UNIQUE(vote_id, user_id)
);
CREATE INDEX pigeon_ballots_vote ON pigeon_ballots(vote_id, updated_at);

CREATE FUNCTION pigeon_ballot_choices_immutable_fn() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'ballot_immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER pigeon_ballot_choices_immutable BEFORE UPDATE OF option_ids, vote_id ON pigeon_ballots
FOR EACH ROW EXECUTE FUNCTION pigeon_ballot_choices_immutable_fn();

CREATE TABLE pigeon_ballot_events (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ballot_id TEXT NOT NULL REFERENCES pigeon_ballots(id) ON DELETE CASCADE,
  option_ids TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  revision BIGINT NOT NULL,
  UNIQUE(ballot_id, revision)
);

CREATE TABLE pigeon_legacy_archive (
  source_table TEXT NOT NULL,
  legacy_id TEXT NOT NULL,
  payload TEXT NOT NULL,
  PRIMARY KEY (source_table, legacy_id)
);
