-- PostgreSQL 版迁移（自 packages/db/migrations/0019_tickets.sql 翻译）。
-- 由 Node 迁移执行器应用；D1 路径不使用本目录。

CREATE TABLE tickets (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticket_number TEXT NOT NULL UNIQUE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  last_user_read_at BIGINT,
  last_admin_read_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  closed_at BIGINT
);
CREATE INDEX tickets_user_updated ON tickets(user_id, updated_at DESC);
CREATE INDEX tickets_status_updated ON tickets(status, updated_at DESC);

CREATE TABLE ticket_messages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  author_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  author_type TEXT NOT NULL,
  body TEXT NOT NULL,
  internal BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL
);
CREATE INDEX ticket_messages_ticket_created ON ticket_messages(ticket_id, created_at);

CREATE TABLE ticket_attachments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  message_id BIGINT REFERENCES ticket_messages(id) ON DELETE CASCADE,
  object_key TEXT NOT NULL UNIQUE,
  file_name TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size_bytes BIGINT NOT NULL,
  created_at BIGINT NOT NULL
);
CREATE INDEX ticket_attachments_ticket ON ticket_attachments(ticket_id);

CREATE TABLE ticket_events (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  type TEXT NOT NULL,
  from_status TEXT,
  to_status TEXT,
  detail TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX ticket_events_ticket_created ON ticket_events(ticket_id, created_at);
