-- PostgreSQL 版迁移（自 packages/db/migrations/0020_ticket_categories.sql 翻译）。
-- 由 Node 迁移执行器应用；D1 路径不使用本目录。

CREATE TABLE ticket_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  hidden BIGINT NOT NULL DEFAULT 0,
  sort_order BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
ALTER TABLE tickets ADD COLUMN category_id BIGINT REFERENCES ticket_categories(id) ON DELETE SET NULL;
ALTER TABLE tickets ADD COLUMN category_name TEXT NOT NULL DEFAULT '';
CREATE INDEX ticket_categories_visible ON ticket_categories(hidden, sort_order, id);
CREATE INDEX tickets_category_id ON tickets(category_id);

INSERT INTO ticket_categories(slug,name,hidden,sort_order,created_at,updated_at)
VALUES
  ('account', '账号与安全', 0, 10, (EXTRACT(EPOCH FROM now())*1000)::BIGINT, (EXTRACT(EPOCH FROM now())*1000)::BIGINT),
  ('texture', '皮肤与材质', 0, 20, (EXTRACT(EPOCH FROM now())*1000)::BIGINT, (EXTRACT(EPOCH FROM now())*1000)::BIGINT),
  ('site', '站点功能', 0, 30, (EXTRACT(EPOCH FROM now())*1000)::BIGINT, (EXTRACT(EPOCH FROM now())*1000)::BIGINT),
  ('other', '其他', 0, 100, (EXTRACT(EPOCH FROM now())*1000)::BIGINT, (EXTRACT(EPOCH FROM now())*1000)::BIGINT);

UPDATE tickets
SET category_id = (SELECT id FROM ticket_categories WHERE ticket_categories.slug = tickets.category),
    category_name = COALESCE((SELECT name FROM ticket_categories WHERE ticket_categories.slug = tickets.category), tickets.category)
WHERE category_name = '';
