-- PostgreSQL 版迁移（自 packages/db/migrations/0028_notification_translations.sql 翻译）。
-- 由 Node 迁移执行器应用；D1 路径不使用本目录。

-- 注意：本目录此前缺失 0024（ai_jobs / task_runs / texture_translations），
-- 在此一并补齐 —— 0028 要放宽 ai_jobs 的 kind CHECK，必须先有 0024 的表。
-- 从未建过这三张表的 PG 部署直接按序执行；已手工建过的部署，
-- 0024 记账后跳过（CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS 幂等）。

-- ── 0024（补齐）─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS task_runs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  ok BIGINT NOT NULL,
  detail TEXT NOT NULL DEFAULT '',
  ran_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS task_runs_name_ran_idx ON task_runs(name, ran_at DESC);

CREATE TABLE IF NOT EXISTS texture_translations (
  tid INTEGER NOT NULL REFERENCES textures(id) ON DELETE CASCADE,
  locale TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (tid, locale)
);

-- ai_jobs 在 SQLite 版带 CHECK 约束；PG 上首次创建即为包含 translate_notification
-- 的新全集，已手工建过旧约束版本的部署由 0028 段重建。
CREATE TABLE IF NOT EXISTS ai_jobs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  kind TEXT NOT NULL,
  tid BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  attempts BIGINT NOT NULL DEFAULT 0,
  next_run_at BIGINT NOT NULL,
  last_error TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ai_jobs_kind_tid_idx ON ai_jobs(kind, tid);
CREATE INDEX IF NOT EXISTS ai_jobs_due_idx ON ai_jobs(status, next_run_at);

-- ── 0028（本迁移）───────────────────────────────────────────────────────────

-- 主键 (content_hash, locale)：译文按模板骨架寻址，与具体通知行无关
CREATE TABLE IF NOT EXISTS notification_translations (
  content_hash TEXT NOT NULL,
  locale TEXT NOT NULL,
  source_title TEXT NOT NULL DEFAULT '',
  source_body TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (content_hash, locale)
);

-- PG 无 CHECK 变更语法，历史旧约束库用 DO 块重建；无约束或新库为空操作。
DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  SELECT conname INTO constraint_name FROM pg_constraint
    WHERE conrelid = 'ai_jobs'::regclass AND contype = 'c' AND pg_get_constraintdef(oid) LIKE '%translate_texture%';
  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE ai_jobs DROP CONSTRAINT %I', constraint_name);
    EXECUTE format(
      'ALTER TABLE ai_jobs ADD CONSTRAINT %I CHECK (kind IN (%L, %L, %L, %L))',
      constraint_name, 'translate_texture', 'moderate_texture_name', 'moderate_texture_description', 'translate_notification'
    );
  END IF;
END $$;

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS template_hash TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS notifications_template_hash_idx ON notifications(template_hash) WHERE template_hash <> '';
