// 队列的 Node 侧适配器：SQLite 当持久化队列，轮询驱动 consumer。
//
// 业务侧契约（零改动迁移的前提）：
//   • producer：email.ts 的 enqueueBroadcastEmail 用 `queue.send(body,
//     { contentType: 'json' })`；search-submissions.ts 的
//     dispatchSearchSubmissions 用 `sendBatch([{ body }])`。
//   • consumer：index.ts 的 `queue(batch)` 里用 `message.ack()` 与
//     `message.retry({ delaySeconds })`，batch 形状是
//     { queue, messages: [{ id, timestamp, body, ack, retry }] }。
//
// 简化点：Workers Queues 的 at-least-once 语义在 Node 单进程里退化为
// "消费成功才删行"；进程崩溃时已取出的消息随下一次轮询重投（行还在）。

import type { SqliteD1 } from './d1/sqlite.ts';
import type { PostgresD1 } from './d1/postgres.ts';
import type { MysqlD1 } from './d1/mysql.ts';
import { dialect } from '@pigeon-skin/db';

// ── 表结构 ───────────────────────────────────────────────────────────────────
// node_jobs(id INTEGER PRIMARY KEY AUTOINCREMENT, queue TEXT, body TEXT,
//           available_at INTEGER, attempts INTEGER DEFAULT 0)
// body 存 JSON 字符串；available_at 是毫秒时间戳。

export async function ensureJobsTable(d1: SqliteD1 | PostgresD1 | MysqlD1): Promise<void> {
  const sql = dialect() === 'postgres'
    ? `CREATE TABLE IF NOT EXISTS node_jobs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    queue TEXT NOT NULL,
    body TEXT NOT NULL,
    available_at BIGINT NOT NULL,
    attempts BIGINT NOT NULL DEFAULT 0
  )`
    : dialect() === 'mysql'
      ? `CREATE TABLE IF NOT EXISTS node_jobs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    queue VARCHAR(128) NOT NULL,
    body TEXT NOT NULL,
    available_at BIGINT NOT NULL,
    attempts BIGINT NOT NULL DEFAULT 0
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`
      : `CREATE TABLE IF NOT EXISTS node_jobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    queue TEXT NOT NULL,
    body TEXT NOT NULL,
    available_at INTEGER NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0
  )`;
  await d1.exec(sql);
}

// ── producer ─────────────────────────────────────────────────────────────────

/** Workers `Queue.send` 第二参的形状（业务代码传 { contentType: 'json' }） */
export interface QueueSendOptions {
  contentType?: string | undefined;
}

export class QueueProducerShim<T = unknown> {
  readonly #d1: SqliteD1;
  readonly #queueName: string;

  constructor(d1: SqliteD1, queueName: string) {
    this.#d1 = d1;
    this.#queueName = queueName;
  }

  async send(body: T, _options?: QueueSendOptions): Promise<void> {
    await this.#d1
      .prepare('INSERT INTO node_jobs (queue, body, available_at, attempts) VALUES (?, ?, ?, 0)')
      .bind(this.#queueName, JSON.stringify(body), Date.now())
      .run();
  }

  /** Workers sendBatch 的消息形状：业务代码只用 { body } */
  async sendBatch(messages: Array<{ body: T }>): Promise<void> {
    for (const message of messages) await this.send(message.body);
  }
}

// ── consumer ─────────────────────────────────────────────────────────────────

/** 对齐 Workers `Message` 的业务代码用到的形状 */
export interface QueueMessageShim<T> {
  readonly id: string;
  readonly timestamp: Date;
  readonly body: T;
  ack(): void;
  retry(options?: { delaySeconds?: number | undefined }): void;
}

/** 对齐 Workers `MessageBatch` */
export interface MessageBatchShim<T> {
  readonly queue: string;
  readonly messages: QueueMessageShim<T>[];
}

export interface QueueConsumerRunnerOptions {
  /** 轮询间隔毫秒数，默认 1000 */
  intervalMs?: number | undefined;
  /** 单批最多取多少条，默认 10（Workers Queues 默认批次也是这个量级） */
  batchSize?: number | undefined;
  /** 最大尝试次数，超过后放弃并 console.error */
  maxAttempts?: number | undefined;
}

interface JobRow {
  id: number;
  queue: string;
  body: string;
  attempts: number;
}

export class QueueConsumerRunner {
  readonly #d1: SqliteD1;
  readonly #consumer: (batch: MessageBatchShim<unknown>) => Promise<void> | void;
  readonly #intervalMs: number;
  readonly #batchSize: number;
  readonly #maxAttempts: number;
  #timer: ReturnType<typeof setInterval> | undefined;
  #running = false;

  constructor(
    d1: SqliteD1,
    consumer: (batch: MessageBatchShim<unknown>) => Promise<void> | void,
    options: QueueConsumerRunnerOptions = {},
  ) {
    this.#d1 = d1;
    this.#consumer = consumer;
    this.#intervalMs = options.intervalMs ?? 1000;
    this.#batchSize = options.batchSize ?? 10;
    this.#maxAttempts = options.maxAttempts ?? 10;
  }

  start(): void {
    if (this.#timer) return;
    // 定时器不阻止进程退出：consumer 停止靠 stop() 显式调用
    // 轮询失败（consumer 抛错/数据库忙）不能变成 unhandledRejection 崩掉进程：
    // Workers 上 queue() 抛错只是消息重投，这里对齐"记日志、下一轮再试"
    this.#timer = setInterval(() => {
      this.pollOnce().catch(error => console.error('[queue] 轮询失败，下一轮重试', error));
    }, this.#intervalMs);
    this.#timer.unref?.();
  }

  stop(): void {
    if (this.#timer) { clearInterval(this.#timer); this.#timer = undefined; }
  }

  /** 手动触发一轮投递（测试与 start 前的即时消费用） */
  async pollOnce(): Promise<void> {
    if (this.#running) return;
    this.#running = true;
    try {
      const due = Date.now();
      const rows = (
        await this.#d1
          .prepare('SELECT id, queue, body, attempts FROM node_jobs WHERE available_at <= ? ORDER BY id LIMIT ?')
          .bind(due, this.#batchSize)
          .all<JobRow>()
      ).results ?? [];
      for (const queueName of [...new Set(rows.map(row => row.queue))]) {
        const batchRows = rows.filter(row => row.queue === queueName);
        await this.#dispatch(queueName, batchRows);
      }
    } finally {
      this.#running = false;
    }
  }

  async #dispatch(queueName: string, rows: JobRow[]): Promise<void> {
    // settled 追踪：consumer 没处理完的消息（既不 ack 也不 retry，比如
    // 异常中断）保底递增 attempts，防止永久卡在队头被无限重投
    const settled = new Set<string>();
    const messages: QueueMessageShim<unknown>[] = rows.map(row => ({
      id: String(row.id),
      timestamp: new Date(),
      body: JSON.parse(row.body) as unknown,
      // ack/retry 是同步打标 + 立即落库；业务代码在 await 之后调用，
      // 不依赖延迟提交
      ack: () => {
        settled.add(String(row.id));
        this.#d1.prepare('DELETE FROM node_jobs WHERE id = ?').bind(row.id).run().catch(error => console.error('[queue] ack 落库失败', error));
      },
      retry: (options?: { delaySeconds?: number | undefined }) => {
        settled.add(String(row.id));
        const delayMs = (options?.delaySeconds ?? 0) * 1000;
        this.#d1
          .prepare('UPDATE node_jobs SET attempts = attempts + 1, available_at = ? WHERE id = ?')
          .bind(Date.now() + delayMs, row.id)
          .run()
          .catch(error => console.error('[queue] retry 落库失败', error));
      },
    }));

    await this.#consumer({ queue: queueName, messages });

    for (const row of rows) {
      if (!settled.has(String(row.id))) {
        await this.#d1.prepare('UPDATE node_jobs SET attempts = attempts + 1 WHERE id = ?').bind(row.id).run();
      }
    }
    await this.#abandonOverLimit(queueName);
  }

  /** 超过最大尝试次数的消息放弃投递 */
  async #abandonOverLimit(queueName: string): Promise<void> {
    const over = (
      await this.#d1
        .prepare('SELECT id, attempts, body FROM node_jobs WHERE queue = ? AND attempts >= ?')
        .bind(queueName, this.#maxAttempts)
        .all<{ id: number; attempts: number; body: string }>()
    ).results ?? [];
    for (const row of over) {
      await this.#d1.prepare('DELETE FROM node_jobs WHERE id = ?').bind(row.id).run();
      console.error(`[queue] 放弃消息：queue=${queueName} id=${row.id} attempts=${row.attempts} body=${row.body.slice(0, 200)}`);
    }
  }
}
